// Generated by CoffeeScript 2.4.1
(function() {
  var express;

  express = require('express');

  module.exports.handler = function(event, context, callback) {
    return callback(null, {
      statusCode: 200,
      body: `${(express != null)}`
    });
  };

}).call(this);
