backend:
    name: github
    repo: VincentPFG/repo-de-test

media_folder: "src/assets/uploads"
public_folder: "uploads"

collections:
-   
    name: "posts"
    label: "Posts"
    folder: "blog"
    create: true
    # slug: "{{slug}}"
    fields:
    -
        label: "Title"
        name: "title"
        widget: "string"
    -
        label: "Publish Date"
        name: "date"
        widget: "date"
    -
        label: "Body"
        name: "body"
        widget: "markdown"
    -
        label: 'Test Image'
        name: 'image'
        widget: 'image'
-
    name: 'test'
    label: 'Test YAML'
    folder: 'test'
    extension: 'yml'
    create: true
    fields:
    -
        label: "Title"
        name: "title"
        widget: "string"
    -
        label: 'Test Image'
        name: 'image'
        widget: 'image'
    -
        label: "Body"
        name: "body"
        widget: "markdown"