backend:
    name: github
    repo: VincentPFG/repo-de-test

media_folder: "~/assets/uploads"
public_folder: "/uploads"

collections:
-   
    name: "posts"
    label: "Posts"
    folder: "blog"
    create: true
    # slug: "{{slug}}"
    fields:
    -
        label: "Title"
        # name: "title"
        widget: "string"
    -
        label: "Publish Date"
        name: "date"
        widget: "date"
    -
        label: "Body"
        name: "body"
        widget: "markdown"